import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import WhatsAppFloating from "@/components/whatsappFloating";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800","900"],
  variable: "--font-geist-sans",
});


export const metadata: Metadata = {
  title: "LetsPrenup",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      cz-shortcut-listen="true"
        className={`${poppins.className} antialiased`}
      >
        <WhatsAppFloating />
        {children}
      </body>
    </html>
  );
}
